GET http://localhost:3000/api/metas/ HTTP/1.1
###
POST http://localhost:3000/api/metas/nueva HTTP/1.1
Content-Type: application/json

{
    "nombreMeta":"Viaje a la playa",
    "descripcionMeta":"Presupuesto para viajar a Cozumel en navidad",
    "fechaInicio": "2026-05-01T06:00:00.000Z",
    "fechaLimite": "2026-12-15T06:00:00.000Z",
    "cantidadActual":1000,
    "cantidadObjetivo":10000,
    "iconoMeta":17
}
###
DELETE http://localhost:3000/api/metas/7 HTTP/1.1