GET http://localhost:3000/api/reglas/ HTTP/1.1
###
POST http://localhost:3000/api/reglas/nueva HTTP/1.1
Content-Type: application/json

{
    "nombreRegla":"Sueldo inicial",
    "descripcionRegla":"Sueldo semanal",
    "cantidadRegla":1200,
    "fechaInicio":"2026-05-01T06:00:00.000Z",
    "frecuencia":"semanal",
    "intervalo":1,
    "diaAplicacion":6
}
###
DELETE http://localhost:3000/api/reglas/3 HTTP/1.1